### ISSUE TITLE
Can this be used on the older Neato's?

### ISSUE THREAD

**Issue by Swiftnesses** [sstadlberger/botvac-wifi#1]
Hi,

Excellent mod, got to love the ESP's :-)

Do you know if this mod could be applied to the older Neato's (I actually own a Vorwerk VR100).

Thanks in advance,

Mark

**Comment by sstadlberger** [comment]
I only have the BotVac 85, so I can't check it, but in principle yes. But it depends on if your board has an exposed serial port. From what I've read on the Internet some versions of the VR100 have a serial connection labeled P3 where you could connect an ESP module. 

See for example here: http://www.roboter-forum.com/showthread.php?3661

Depending on the serial connection you may have to change the connection speed (see here: https://github.com/sstadlberger/botvac-wifi/blob/52fbc242da4201e009124b31141e1de037e9baa5/botvac-wifi.ino#L105-L107)

The ESP module in this code just acts as an transparent serial to websocket bridge and can be used in different applications (not just robot vacuums).

**Comment by jonvic1891** [comment]
Hi, do you know if plugging  a NRF24LU1 usb from module directly into the USB port would work, it has a slightly higher operating voltage of 3.7 to 5.5 volts but would mean no soldering etc. Also would it take the software. Reason why I'm going RF is that I think I could controll it with my Broadlink RM pro as that is hooked into my smartthings hub so I don't need the ST shield.

**Comment by sstadlberger** [comment]
I'm not really familiar with the NRF24LU1 module but from I read it should not work for the following reasons:

- Both the BotVac and the NRF24LU1 module need to be plugged into a host device (i.e. a computer like device that also supplies power). To use a NRF24LU1 module directly on the BotVac's USB port it would need to act as a USB host controller for the BotVac and also contain the appropriate drivers.
- The software should also not work, because all it is doing is establishing a websocket connection via WiFi. That is completely than 2.4GHz RF.
- Only connect 3.3V devices to 3.3V devices. If you use a different voltage on the BotVac board than it was designed for, then you have a very high probability to instantly destroy your BotVac mainboard.

Sorry that I could not be more helpful, but I designed this solution for just a single use case. If you want to expand it to other use cases you are very welcome to contribute.
